server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'herapantera'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
